# Generated by Django 5.0 on 2023-12-28 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0002_tbl_category_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admin_name', models.CharField(max_length=50)),
                ('admin_con', models.CharField(max_length=50)),
                ('admin_mail', models.CharField(max_length=50)),
                ('admin_pass', models.CharField(max_length=50)),
            ],
        ),
    ]
