# Generated by Django 5.0 on 2024-01-05 06:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0002_rename_student_tbl_student'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_student',
        ),
    ]
