# Generated by Django 5.0 on 2024-01-13 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0004_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_student',
        ),
    ]
